language: python

python:
  - "2.7"

install:
  - pip install . --use-mirrors
  - wget "http://downloads.sourceforge.net/project/python-metar/python-metar/v1.4.0/metar-1.4.0.tar.gz?r=&ts=1407175653&use_mirror=freefr" -O metar-1.4.0.tar.gz
  -	pip install metar-1.4.0.tar.gz
  - pip install -r requirements/test.txt --allow-external

script: 
  - make test

after_success:
  - coveralls